import type { Locale } from "./i18n"

export type AssessmentCopy = {
  metaTitle: string
  metaDescription: string
  backHome: string
  title: string
  lead: string
  resultTitle: string
  opportunity: string
  complexity: string
  points: string
  bandLow: string
  bandMedium: string
  bandHigh: string
  complexityS: string
  complexityM: string
  complexityL: string
  resultDisclaimer: string
  print: string
  s1: { title: string; company: string; industry: string; productionType: string; ptSerial: string; ptProject: string; ptMto: string; ptMts: string; employees: string; plants: string; certIso: string; certIatf: string; certOther: string; certOtherPh: string }
  s2: { title: string; machines: string; workCenters: string; productCount: string; shifts: string; cycle: string; track: string; trExcel: string; trPaper: string; trErp: string; trMes: string; trNone: string }
  s3: { title: string; decisions: string; dExp: string; dExcel: string; dRep: string; dRt: string; has: string; erp: string; scada: string; mes: string; prob: string; pData: string; pLate: string; pManual: string; pOee: string; pUnk: string }
  s4: { title: string; oeeQ: string; oeeYes: string; oeeNo: string; oeeHow: string; oMan: string; oSys: string; dPct: string; sPct: string; uPct: string; losses: string; lBreak: string; lStop: string; lSlow: string; lScrap: string; foot: string }
  s5: { title: string; ncr: string; capa: string; have: string; pfmea: string; controlPlan: string; trace: string; loop: string; loopYes: string; loopPartial: string; loopNo: string; loopUnk: string; repeat: string; repO: string; repR: string; repU: string }
  s6: { title: string; mtype: string; mtR: string; mtP: string; mtPr: string; have: string; hFault: string; hPm: string; hNone: string; unplan: string; uHigh: string; uMed: string; uLow: string; foot: string }
  s7: { title: string; track: string; tAtt: string; tPerf: string; tNeither: string; have: string; hMat: string; hTrain: string; hScat: string; link: string; lYes: string; lPartial: string; lNo: string; lUnk: string }
  s8: { title: string; how: string; hExcel: string; hErp: string; hMan: string; hMix: string; real: string; rYes: string; rNo: string; cap: string; cYes: string; cPart: string; cNo: string }
  s9: { title: string; imPlc: string; imEth: string; imSc: string; canRead: string; crSt: string; crCyc: string; crAl: string; crNo: string; net: string; nSt: string; nPart: string; nWeak: string }
  s10: { title: string; pRealtime: string; pOee: string; pScrap: string; pDown: string; pDig: string; pAuto: string; pAi: string; oneToFive: string }
  s11: { title: string; goal: string; gProd: string; gCost: string; gControl: string; gDig: string; gIatf: string; gOther: string; gOtherPh: string; expect: string }
  s12: { title: string; budget: string; b10: string; b50: string; b100: string; b100p: string; bUnsure: string; time: string; tAsap: string; t3: string; t6: string; tDeadline: string; deadlinePh: string }
  s13: { title: string; notes: string; notesPh: string }
  next: { title: string; b1: string; b2: string; b3: string }
}

const en: AssessmentCopy = {
  metaTitle: "Digitalization assessment | Operonix",
  metaDescription:
    "Short questionnaire to scope production digitalization, MES, OEE, and quality—orientational pricing context for your Operonix quote.",
  backHome: "Back to home",
  title: "Production digitalization — assessment for scope & quote",
  lead:
    "This is not a contract: it gives us a structured picture of your production, pain points, and IT—so we can return an orientational offer (modules, phases) faster. A short follow-up call may still be needed for validation.",
  resultTitle: "Orientational result (for our sales team)",
  opportunity: "Opportunity index (0–100)",
  complexity: "Indicative delivery size",
  points: "points",
  bandLow: "LOW — education / small pilot or later",
  bandMedium: "MEDIUM — typical phase 1 fit",
  bandHigh: "HIGH — strong fit; confirm implementation risk in call",
  complexityS: "S — one site, pilot / focused scope",
  complexityM: "M — several lines, integrations or more modules",
  complexityL: "L — multi-plant, deep integrations, broad rollout",
  resultDisclaimer:
    "This score does not set price or contract terms. The Operonix team may adjust the model. Budget and scope are confirmed in the written proposal.",
  print: "Print / Save as PDF",
  s1: {
    title: "1. Company",
    company: "Company name",
    industry: "Industry",
    productionType: "Production type (tick all that apply)",
    ptSerial: "Repetitive / serial",
    ptProject: "Project / engineer-to-order",
    ptMto: "MTO (make-to-order)",
    ptMts: "MTS (make-to-stock)",
    employees: "Number of employees (approx.)",
    plants: "Number of production sites / plants",
    certIso: "ISO",
    certIatf: "IATF",
    certOther: "Other",
    certOtherPh: "Other certificate (name)",
  },
  s2: {
    title: "2. Production",
    machines: "Number of machines (approx.)",
    workCenters: "Number of work centers",
    productCount: "Number of product families / SKU (order of magnitude)",
    shifts: "Shifts per day",
    cycle: "Typical production cycle (e.g. hours or days per batch)",
    track: "How you track production today (multiple options possible)",
    trExcel: "Excel",
    trPaper: "Paper",
    trErp: "ERP",
    trMes: "MES",
    trNone: "We do not track / unsure",
  },
  s3: {
    title: "3. Digital maturity",
    decisions: "How operational decisions are made (multiple options)",
    dExp: "Experience / judgment",
    dExcel: "Excel / spreadsheets",
    dRep: "Periodic reports (daily/weekly)",
    dRt: "Real-time or near real-time data",
    has: "You have in place (tick)",
    erp: "ERP (name)",
    scada: "SCADA / shop-floor visualization",
    mes: "MES (name if any)",
    prob: "Biggest current pain (tick up to two)",
    pData: "Inconsistent or wrong data",
    pLate: "Information arrives too late",
    pManual: "Double entry / too much manual work",
    pOee: "Unknown losses (OEE, downtime…)",
    pUnk: "We are not sure / no visibility",
  },
  s4: {
    title: "4. OEE & losses",
    oeeQ: "Do you track OEE or a similar KPI by line/area?",
    oeeYes: "Yes",
    oeeNo: "No",
    oeeHow: "If yes, how?",
    oMan: "Manually (Excel, paper, boards)",
    oSys: "In a system (MES/ERP)",
    dPct: "Downtime (approx. %, optional)",
    sPct: "Scrap / quality loss (approx. %, optional)",
    uPct: "Utilization / performance (approx. %, optional)",
    losses: "Largest current losses (tick)",
    lBreak: "Breakdowns / maintenance",
    lStop: "Planned and unplanned stops",
    lSlow: "Low speed / long cycles",
    lScrap: "Scrap / rework",
    foot: "Operonix: OEE/OOE, TEEP, and analytics are offered by subscription level.",
  },
  s5: {
    title: "5. Quality (QMS / IATF)",
    ncr: "NCR: how (tool / process, short text)",
    capa: "CAPA: how (short text)",
    have: "You have (tick)",
    pfmea: "PFMEA (where: …)",
    controlPlan: "Control plan",
    trace: "Traceability (lot/serial as required)",
    loop: "Closed loop from event to close-out in one system?",
    loopYes: "Yes, largely",
    loopPartial: "Only partial / fragmented",
    loopNo: "No",
    loopUnk: "Not sure / fragmented tools",
    repeat: "Do the same quality issues repeat?",
    repO: "Often",
    repR: "Rarely",
    repU: "We do not know / no data",
  },
  s6: {
    title: "6. Maintenance",
    mtype: "Dominant maintenance style",
    mtR: "Reactive (mostly run-to-fail / urgent)",
    mtP: "Preventive (PM calendar)",
    mtPr: "Predictive (data / condition-based)",
    have: "You have (tick)",
    hFault: "Central fault / work order log",
    hPm: "PM plan in a system we actually use",
    hNone: "None of the above in one place",
    unplan: "Unplanned stoppage frequency (subjective)",
    uHigh: "High",
    uMed: "Medium",
    uLow: "Low",
    foot: "Operonix Maintenance: work orders, assets, and notifications in one CMMS (module-based).",
  },
  s7: {
    title: "7. Workforce",
    track: "You track (tick)",
    tAtt: "Time & attendance / presence",
    tPerf: "Output / productivity per shift",
    tNeither: "Neither in one place",
    have: "You have (tick)",
    hMat: "Skills / competency matrix (formal)",
    hTrain: "Central training records",
    hScat: "Scattered (paper, e-mail, HR only)",
    link: "Can you link in data: operator ↔ product ↔ quality?",
    lYes: "Yes",
    lPartial: "Partially",
    lNo: "No",
    lUnk: "Not sure",
  },
  s8: {
    title: "8. Production planning",
    how: "How is the plan made (dominant method)?",
    hExcel: "Excel",
    hErp: "ERP",
    hMan: "Manual (board, paper)",
    hMix: "Mixed",
    real: "Is the plan realistic on the floor?",
    rYes: "Mostly matches reality",
    rNo: "Often unrealistic; needs re-plan or firefighting",
    cap: "Do you know true line capacity (realistic takt / OEE effect)?",
    cYes: "Yes, we measure it",
    cPart: "Partly / rules of thumb",
    cNo: "No / guess",
  },
  s9: {
    title: "9. Shop floor & IT",
    imPlc: "Machines with PLC (most lines)",
    imEth: "Ethernet to machines / line networks",
    imSc: "Existing SCADA on site",
    canRead: "You can (or would pilot) read from machines:",
    crSt: "Run/stop / state",
    crCyc: "Cycle or piece count",
    crAl: "Alarms for downtime reasons",
    crNo: "Not reliably / not yet",
    net: "Network quality in the plant for cloud/MES",
    nSt: "Stable",
    nPart: "Partial / sometimes drops",
    nWeak: "Weak (limits real-time)",
  },
  s10: {
    title: "10. Priorities (1 = low, 5 = high importance)",
    pRealtime: "Real-time production visibility",
    pOee: "OEE / loss analysis",
    pScrap: "Reduce scrap / rework",
    pDown: "Reduce unplanned stops",
    pDig: "One digital system (one backbone)",
    pAuto: "Workflow automation and notifications",
    pAi: "AI-assisted analysis / prioritization",
    oneToFive: "Rate 1–5",
  },
  s11: {
    title: "11. Business goals",
    goal: "Main project goal (multiple)",
    gProd: "Productivity / throughput",
    gCost: "Lower operating cost / less waste",
    gControl: "Control & traceability",
    gDig: "General digitalization of shop floor",
    gIatf: "IATF / customer / audit",
    gOther: "Other (short)",
    gOtherPh: "Other (specify)",
    expect: "Expected result in 1–2 sentences (optional)",
  },
  s12: {
    title: "12. Budget & time (indicative only)",
    budget: "Planned or acceptable budget (orientational range)",
    b10: "Up to ~10k EUR",
    b50: "10k – 50k EUR",
    b100: "50k – 100k EUR",
    b100p: "100k+ EUR or multi-year program",
    bUnsure: "Prefer a proposal first; no range yet",
    time: "Desired start of phase 1",
    tAsap: "ASAP (within a month)",
    t3: "Within ~3 months",
    t6: "6+ months",
    tDeadline: "Fixed target date (fill below)",
    deadlinePh: "e.g. Q4, plant launch date…",
  },
  s13: {
    title: "13. Other notes",
    notes: "Free text: existing vendors, IT constraints, must-have integrations, number of key users…",
    notesPh: "Type here…",
  },
  next: {
    title: "What happens after you send this (copy for your e-mail to us)",
    b1: "You send the completed form (export PDF, or e-mail) to the Operonix contact you were given.",
    b2: "We reply within a few business days with an orientational scope (modules + phases) and, where applicable, indicative options.",
    b3: "If needed, we schedule a short call or a half-day on-site/online to validate assumptions and finalize the offer.",
  },
}

const bs: AssessmentCopy = {
  metaTitle: "Procjena digitalizacije | Operonix",
  metaDescription:
    "Kratki upitnik za opseg proizvodnje, MES, OEE i kvaliteta – kontekst za orijentacionu ponudu Operonix.",
  backHome: "Natrag na početnu",
  title: "Digitalizacija proizvodnje — upitnik za opseg i ponudu",
  lead:
    "Ovo nije ugovor: daje nam strukturiranu sliku o proizvodnji, ‚boli‘ i IT okruženju, kako bismo brže vratili orijentacionu ponudu (moduli, faze). Kratki follow-up poziv i dalje može biti potreban radi validacije.",
  resultTitle: "Orijentacioni rezultat (za naš tim prodaje / ponude)",
  opportunity: "Indeks prilike (0–100)",
  complexity: "Indikativna veličina isporuke",
  points: "bodova",
  bandLow: "LOW — edukacija / mali pilot ili kasnije",
  bandMedium: "MEDIUM — tipičan fit za fazu 1",
  bandHigh: "HIGH — jaka prilika; u pozivu potvrdite rizik isporuke",
  complexityS: "S — jedan pogon, pilot / fokus",
  complexityM: "M — više linija, integracije ili više modula",
  complexityL: "L — više lokacija, duboke integracije, široki rollout",
  resultDisclaimer:
    "Ovaj skor ne određuje cijenu niti ugovor. Operonix tim može korigirati model. Budžet i opseg u pisanoj ponudi su presudni.",
  print: "Štampaj / spremi kao PDF",
  s1: {
    title: "1. Osnovni podaci o kompaniji",
    company: "Naziv kompanije",
    industry: "Industrija / djelatnost",
    productionType: "Tip proizvodnje (označite sve što važi)",
    ptSerial: "Serijska / masovna",
    ptProject: "Projektna / ETO",
    ptMto: "MTO (proizvodnja na narudžbu)",
    ptMts: "MTS (na zalihu)",
    employees: "Broj zaposlenih (procjena)",
    plants: "Broj proizvodnih lokacija / pogona",
    certIso: "ISO",
    certIatf: "IATF",
    certOther: "Drugo",
    certOtherPh: "Drugo (naziv sertifikata)",
  },
  s2: {
    title: "2. Proizvodnja",
    machines: "Broj mašina (procjena)",
    workCenters: "Broj radnih centara",
    productCount: "Broj proizvoda / porodica (red veličine)",
    shifts: "Broj smjena dnevno",
    cycle: "Tipičan ciklus (npr. sati / dani po seriji)",
    track: "Kako danas pratite proizvodnju (može više)",
    trExcel: "Excel",
    trPaper: "Papir",
    trErp: "ERP",
    trMes: "MES",
    trNone: "Ne pratimo / ne znamo",
  },
  s3: {
    title: "3. Digitalna zrelost",
    decisions: "Kako donosite poslovne/operativne odluke (može više)",
    dExp: "Iskustvo / procjena",
    dExcel: "Excel / tabele",
    dRep: "Periodični izvještaji (dnevni/sedmični)",
    dRt: "Podaci u realnom ili bliskom vremenu",
    has: "Imate (označite)",
    erp: "ERP (naziv)",
    scada: "SCADA / vizualizacija na pogonu",
    mes: "MES (naziv, ako imate)",
    prob: "Najveći problem trenutno (do dva)",
    pData: "Netačni / nekonsistentni podaci",
    pLate: "Kašnjenje informacija",
    pManual: "Dvostruki unos / previše ručnog rada",
    pOee: "Nepoznati gubici (OEE, zastoji…)",
    pUnk: "Ne znamo / nema vidljivosti",
  },
  s4: {
    title: "4. OEE / gubici",
    oeeQ: "Pratite li OEE ili sličan KPI po liniji/zoni?",
    oeeYes: "Da",
    oeeNo: "Ne",
    oeeHow: "Ako da, kako?",
    oMan: "Ručno (Excel, papir, table)",
    oSys: "U sistemu (MES/ERP)",
    dPct: "Downtime (približno %, neobavezno)",
    sPct: "Scrap / gubitak kvaliteta (približno %)",
    uPct: "Iskorištenost / performanse (približno %)",
    losses: "Najveći gubici trenutno (označite)",
    lBreak: "Kvarovi / održavanje",
    lStop: "Planirani i neplanirani zastoji",
    lSlow: "Sporo / mali ciklusi",
    lScrap: "Škart / rework",
    foot: "Operonix: OOE/OEE, TEEP i analitika — prema nivou pretplate.",
  },
  s5: {
    title: "5. Kvalitet (QMS / IATF)",
    ncr: "NCR: kako (alat / proces, kratko)",
    capa: "CAPA: kako (kratko)",
    have: "Imate (označite)",
    pfmea: "PFMEA (gdje: …)",
    controlPlan: "Kontrolni plan",
    trace: "Sljedivost (lot/serija po zahtjevu)",
    loop: "Closed-loop do zatvaranja u jednom sistemu?",
    loopYes: "Da, uglavnom",
    loopPartial: "Djelimično / rastureno",
    loopNo: "Ne",
    loopUnk: "Ne znamo / alati rastrkani",
    repeat: "Da li se ista pitanja kvaliteta ponavljaju?",
    repO: "Često",
    repR: "Rijetko",
    repU: "Ne znamo / nemamo podatke",
  },
  s6: {
    title: "6. Održavanje",
    mtype: "Dominantan tip održavanja",
    mtR: "Reaktivno (uglavnom kad stane)",
    mtP: "Preventivno (PM kalendar)",
    mtPr: "Prediktivno (podaci / stanje)",
    have: "Imate (označite)",
    hFault: "Centralan zapis kvarova / radnih naloga",
    hPm: "PM plan u sistemu koji se stvarno koristi",
    hNone: "Niti jedno na jednom mjestu",
    unplan: "Učestalost neplaniranih zastoja (subjektivno)",
    uHigh: "Visoka",
    uMed: "Srednja",
    uLow: "Niska",
    foot: "Operonix Održavanje: radni nalozi, imovina, notifikacije u CMMS-u (modulski).",
  },
  s7: {
    title: "7. Radna snaga",
    track: "Pratite (označite)",
    tAtt: "Dolazak / prisutnost (T&A)",
    tPerf: "Izlaz / učinak po smjeni",
    tNeither: "Niti jedno u jednom mjestu",
    have: "Imate (označite)",
    hMat: "Matricu kompetencija (formaliziranu)",
    hTrain: "Centralan zapis obuka",
    hScat: "Rastureno (mail, HR, papir…)",
    link: "Možete li povezati: operater ↔ proizvod ↔ kvalitet u podatku?",
    lYes: "Da",
    lPartial: "Djelomično",
    lNo: "Ne",
    lUnk: "Ne znamo",
  },
  s8: {
    title: "8. Planiranje proizvodnje",
    how: "Kako se plan pravi (dominantno)?",
    hExcel: "Excel",
    hErp: "ERP",
    hMan: "Ručno (tabla, papir)",
    hMix: "Miješano",
    real: "Koliko je plan realan u praksi?",
    rYes: "Uglavnom se drži stvarnosti",
    rNo: "Često nerealan, treba preplanu / gašenje",
    cap: "Znate li stvarni kapacitet (takt, OEE učinak)?",
    cYes: "Da, mjerimo",
    cPart: "Djelimično / pravila palca",
    cNo: "Ne / pogađamo",
  },
  s9: {
    title: "9. Infrastruktura (pogon + IT)",
    imPlc: "Mašine/linije s PLC-om (većina)",
    imEth: "Ethernet do mašina / odsjeka mreža",
    imSc: "Postojeći SCADA na lokaciji",
    canRead: "Što je moguće očitati (ili biste pilirotili):",
    crSt: "Run/stop / stanje rada",
    crCyc: "Ciklus / broj komada",
    crAl: "Alarmi s razlozima",
    crNo: "Ne pouzdano / još ne",
    net: "Kvaliteta mreže (za cloud / MES)",
    nSt: "Stabilna",
    nPart: "Djelimična / ponekad puca",
    nWeak: "Slaba (ograničava real-time)",
  },
  s10: {
    title: "10. Prioriteti (1 = nisko, 5 = visoko)",
    pRealtime: "Real-time uvid u proizvodnju",
    pOee: "OEE / analiza gubitaka",
    pScrap: "Smanjenje škarta / reworka",
    pDown: "Smanjenje neplaniranih zastoja",
    pDig: "Jedan digitalni sustav (okosnica)",
    pAuto: "Automatizacija toka/ notifikacija",
    pAi: "AI pomoć u analizi / prioritetima",
    oneToFive: "Ocijenite 1–5",
  },
  s11: {
    title: "11. Poslovni ciljevi",
    goal: "Glavni cilj projekta (može više)",
    gProd: "Produktivnost / protok (throughput)",
    gCost: "Smanjenje operativnih troškova / otpada",
    gControl: "Kontrola / sljedivost",
    gDig: "Opća digitalizacija pogona",
    gIatf: "IATF / kupac / audit",
    gOther: "Drugo (kratko)",
    gOtherPh: "Drugo (navesti)",
    expect: "Očekivani rezultat u 1–2 rečenice (neobavezno)",
  },
  s12: {
    title: "12. Budžet i vremenski okvir (samo orijentacija)",
    budget: "Planirani / prihvatljivi budžet (gruba traka)",
    b10: "Do ~10k EUR",
    b50: "10k – 50k EUR",
    b100: "50k – 100k EUR",
    b100p: "100k+ EUR ili program u više godina",
    bUnsure: "Želimo prvo procjenu; nema trake",
    time: "Željeni početak faze 1",
    tAsap: "Što prije (do 1 mjesec)",
    t3: "Do ~3 mjeseca",
    t6: "6+ mjeseci",
    tDeadline: "Fiksni rok (ispod)",
    deadlinePh: "npr. Q4, start nove linije…",
  },
  s13: {
    title: "13. Dodatne napomene",
    notes: "Slobodan tekst: postojeći vendori, IT ograničenja, integracije, broj korisnika…",
    notesPh: "Ovdje napišite…",
  },
  next: {
    title: "Šta slijedi nakon slanja (tekst za e-mail klijentu)",
    b1: "Popunjeno pošaljete (PDF, ili e-mail) na Operonix kontakt koji vam je dat.",
    b2: "Odgovaramo u nekoliko radnih dana s orijentacionim opsegom (moduli + faze) i, gdje ima smisla, i opcijama cijene.",
    b3: "Po potrebi: kratki poziv ili poludan na pogonu/online kako bismo potvrdili pretpostavke i zatvorili ponudu.",
  },
}

export function getAssessmentCopy(locale: Locale): AssessmentCopy {
  return locale === "bs" ? bs : en
}
